CREATE TABLE "morning_briefings" (
	"id" serial PRIMARY KEY NOT NULL,
	"zone_id" integer NOT NULL,
	"zone_slug" text NOT NULL,
	"briefing_date" text NOT NULL,
	"danger_rating" text,
	"danger_level" integer,
	"danger_above_treeline_rating" text,
	"danger_above_treeline_level" integer,
	"danger_near_treeline_rating" text,
	"danger_near_treeline_level" integer,
	"danger_below_treeline_rating" text,
	"danger_below_treeline_level" integer,
	"avalanche_problems" text[],
	"alert_action" text NOT NULL,
	"explanation" text,
	"model" text,
	"status" text DEFAULT 'ready' NOT NULL,
	"review_status" text,
	"reviewer_name" text,
	"reviewed_at" timestamp,
	"original_explanation" text,
	"reviewer_notes" text,
	"generated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "morning_briefings_zone_id_briefing_date_unique" UNIQUE("zone_id","briefing_date")
);
